// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin-login" | "/avaliadores" | "/cargos" | "/categorias" | "/configuracoes" | "/encarregados" | "/igrejas" | "/imprimir-resultado/[id]" | "/imprimir-resultado/lote" | "/imprimir-teste/[id]" | "/instrumentos" | "/login" | "/ministerios" | "/painel-testes" | "/portal" | "/portal/cadastro-teste" | "/portal/cadastro-teste/[id]" | "/portal/cadastro-teste/[id]/imprimir" | "/portal/pre-avaliacao" | "/portal/pre-avaliacao/avaliar" | "/portal/pre-avaliacao/resultado" | "/setores" | "/tipos-teste"
type AppRouteHandlerRoutes = "/api/config/favicon" | "/api/config/logo" | "/api/pdf/lote" | "/api/pdf/musico" | "/api/pdf/organista" | "/api/pdf/troca-instrumento"
type PageRoutes = never
type LayoutRoutes = "/" | "/portal"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin-login": {}
  "/api/config/favicon": {}
  "/api/config/logo": {}
  "/api/pdf/lote": {}
  "/api/pdf/musico": {}
  "/api/pdf/organista": {}
  "/api/pdf/troca-instrumento": {}
  "/avaliadores": {}
  "/cargos": {}
  "/categorias": {}
  "/configuracoes": {}
  "/encarregados": {}
  "/igrejas": {}
  "/imprimir-resultado/[id]": { "id": string; }
  "/imprimir-resultado/lote": {}
  "/imprimir-teste/[id]": { "id": string; }
  "/instrumentos": {}
  "/login": {}
  "/ministerios": {}
  "/painel-testes": {}
  "/portal": {}
  "/portal/cadastro-teste": {}
  "/portal/cadastro-teste/[id]": { "id": string; }
  "/portal/cadastro-teste/[id]/imprimir": { "id": string; }
  "/portal/pre-avaliacao": {}
  "/portal/pre-avaliacao/avaliar": {}
  "/portal/pre-avaliacao/resultado": {}
  "/setores": {}
  "/tipos-teste": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/portal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
