// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(admin)/avaliadores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/avaliadores">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/avaliadores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/cargos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cargos">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/cargos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/categorias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categorias">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/categorias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/encarregados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/encarregados">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/encarregados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/igrejas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/igrejas">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/igrejas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/instrumentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instrumentos">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/instrumentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/ministerios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministerios">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/ministerios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/painel-testes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/painel-testes">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/painel-testes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/setores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setores">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/setores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/tipos-teste/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tipos-teste">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/tipos-teste/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/admin-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/admin-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/imprimir-resultado/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imprimir-resultado/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/imprimir-resultado/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/imprimir-resultado/lote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imprimir-resultado/lote">> = Specific
  const handler = {} as typeof import("../../../src/app/imprimir-resultado/lote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/imprimir-teste/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imprimir-teste/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/imprimir-teste/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/cadastro-teste/[id]/imprimir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/cadastro-teste/[id]/imprimir">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/cadastro-teste/[id]/imprimir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/cadastro-teste/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/cadastro-teste/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/cadastro-teste/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/cadastro-teste/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/cadastro-teste">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/cadastro-teste/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/pre-avaliacao/avaliar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/pre-avaliacao/avaliar">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/pre-avaliacao/avaliar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/pre-avaliacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/pre-avaliacao">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/pre-avaliacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/pre-avaliacao/resultado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/pre-avaliacao/resultado">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/pre-avaliacao/resultado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/config/favicon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/favicon">> = Specific
  const handler = {} as typeof import("../../../src/app/api/config/favicon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/config/logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/logo">> = Specific
  const handler = {} as typeof import("../../../src/app/api/config/logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pdf/lote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf/lote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pdf/lote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pdf/musico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf/musico">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pdf/musico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pdf/organista/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf/organista">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pdf/organista/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pdf/troca-instrumento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf/troca-instrumento">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pdf/troca-instrumento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../src/app/portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
